<?
$PERM["buyer_profile"]["G8"]="D";
$PERM["buyer_profile"]["*"]="D";
$PERM["buyer_profile"]["G6"]="X";
$PERM["customer_profile"]["G8"]="D";
$PERM["customer_profile"]["G7"]="X";
$PERM["customer_profile"]["G5"]="D";
$PERM["customer_profile"]["*"]="D";
$PERM["ads"]["G8"]="X";
$PERM["index.php"]["G5"]="W";
$PERM["index.php"]["G8"]="X";
$PERM["/"]["*"]="R";
$PERM["/"]["G8"]="X";
$PERM["about_service"]["8"]="X";
$PERM["bitrix"]["8"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
?>